return {
  ["workshop-347079953"]={
    ["configuration_options"]={ ["DFV_Language"]="EN", ["DFV_MinimalMode"]="default" },
    ["enabled"]=true 
  },
  ["workshop-362175979"]={ ["configuration_options"]={ ["Draw over FoW"]="disabled" }, ["enabled"]=true },
  ["workshop-375859599"]={
    ["configuration_options"]={
      ["divider"]=5,
      ["random_health_value"]=0,
      ["random_range"]=0,
      ["show_type"]=0,
      ["unknwon_prefabs"]=1,
      ["use_blacklist"]=true 
    },
    ["enabled"]=true 
  },
  ["workshop-378160973"]={
    ["configuration_options"]={
      ["ENABLEPINGS"]=true,
      ["FIREOPTIONS"]=2,
      ["OVERRIDEMODE"]=false,
      ["SHAREMINIMAPPROGRESS"]=true,
      ["SHOWFIREICONS"]=true,
      ["SHOWPLAYERICONS"]=true,
      ["SHOWPLAYERSOPTIONS"]=2 
    },
    ["enabled"]=true 
  },
  ["workshop-462434129"]={
    ["configuration_options"]={
      ["MOD_RESTART_ALLOW_KILL"]=true,
      ["MOD_RESTART_ALLOW_RESTART"]=true,
      ["MOD_RESTART_ALLOW_RESURRECT"]=true,
      ["MOD_RESTART_CD_BONUS"]=0,
      ["MOD_RESTART_CD_KILL"]=3,
      ["MOD_RESTART_CD_MAX"]=0,
      ["MOD_RESTART_CD_RESTART"]=5,
      ["MOD_RESTART_CD_RESURRECT"]=7,
      ["MOD_RESTART_FORCE_DROP_MODE"]=0,
      ["MOD_RESTART_IGNORING_ADMIN"]=true,
      ["MOD_RESTART_MAP_SAVE"]=2,
      ["MOD_RESTART_RESURRECT_HEALTH"]=0,
      ["MOD_RESTART_TRIGGER_MODE"]=1,
      ["MOD_RESTART_WELCOME_TIPS"]=true,
      ["MOD_RESTART_WELCOME_TIPS_TIME"]=6 
    },
    ["enabled"]=true 
  },
  ["workshop-466732225"]={ ["configuration_options"]={  }, ["enabled"]=true },
  ["workshop-666155465"]={
    ["configuration_options"]={
      ["food_estimation"]=-1,
      ["food_order"]=0,
      ["food_style"]=0,
      ["lang"]="auto",
      ["show_food_units"]=-1 
    },
    ["enabled"]=true 
  },
  ["workshop-758532836"]={
    ["configuration_options"]={
      ["AUTOPAUSECONSOLE"]=false,
      ["AUTOPAUSEMAP"]=false,
      ["AUTOPAUSESINGLEPLAYERONLY"]=true,
      ["ENABLECLIENTPAUSE"]=false,
      ["ENABLEHOTKEY"]=false,
      ["KEYBOARDTOGGLEKEY"]="P" 
    },
    ["enabled"]=true 
  } 
}